feat: git hooks for post-checkout and pre-push #1077

diff --git a/scripts/git/pre-push b/scripts/git/pre-push
--- a/scripts/git/pre-push
+++ b/scripts/git/pre-push
@@ -1,5 +1,17 @@
 #!/bin/bash
 
-composer run test
+composer test
+COMPOSER_TEST_EC=$?
 
 npm test -- --silent
+NPM_TEST_EC=$?
+
+let "ERROR = $COMPOSER_TEST_EC + $NPM_TEST_EC"
+
+if [ ${ERROR} -eq "0" ]
+then
+    echo "all good! 😍"
+else
+    echo "push aborted 👎 | error $ERROR"
+    exit ${ERROR}
+fi
